LangString addOrReinstall ${LANG_HUNGARIAN} "Összetevők hozzáadása / újratelepítése"
LangString alreadyInstalled ${LANG_HUNGARIAN} "Már telepítve van"
LangString alreadyInstalledLong ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} ${VERSION} már telepítve van. Válaszd ki a kívánt műveletet, és kattints a Tovább gombra."
LangString appRunning ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} fut! Előbb zárd be, aztán próbáld újra."
LangString appRunningOkKill ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} fut!$\nAz OK gombbal bezárhatod."
LangString chooseMaintenanceOption ${LANG_HUNGARIAN} "Válaszd ki a karbantartási műveletet."
LangString choowHowToInstall ${LANG_HUNGARIAN} "Válaszd ki, hogyan szeretnéd telepíteni: ${PRODUCTNAME}."
LangString createDesktop ${LANG_HUNGARIAN} "Parancsikon az asztalra"
LangString dontUninstall ${LANG_HUNGARIAN} "Ne távolítsa el"
LangString dontUninstallDowngrade ${LANG_HUNGARIAN} "Ne távolítsa el (ennél a telepítőnél a régebbi verzióra váltás eltávolítás nélkül nem engedélyezett)"
LangString failedToKillApp ${LANG_HUNGARIAN} "Nem sikerült bezárni: ${PRODUCTNAME}. Zárd be kézzel, és próbáld újra."
LangString newerVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy újabb verziója már telepítve van. Régebbi verziót nem ajánlott telepíteni. Ha mégis ezt szeretnéd, előbb távolítsd el a jelenlegi verziót. Válaszd ki a kívánt műveletet, és kattints a Tovább gombra."
LangString older ${LANG_HUNGARIAN} "régebbi"
LangString olderOrUnknownVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy $R4 verziója van telepítve. Telepítés előtt ajánlott eltávolítani. Válaszd ki a kívánt műveletet, és kattints a Tovább gombra."
LangString silentDowngrades ${LANG_HUNGARIAN} "Ennél a telepítőnél a régebbi verzióra váltás nem engedélyezett, ezért a csendes telepítés nem folytatható. Használd a grafikus telepítőt.$\n"
LangString unableToUninstall ${LANG_HUNGARIAN} "Az eltávolítás nem sikerült!"
LangString uninstallApp ${LANG_HUNGARIAN} "${PRODUCTNAME} eltávolítása"
LangString uninstallBeforeInstalling ${LANG_HUNGARIAN} "Eltávolítás telepítés előtt"
LangString unknown ${LANG_HUNGARIAN} "ismeretlen"
LangString deleteAppData ${LANG_HUNGARIAN} "Az alkalmazás adatainak törlése (a haladásod is!)"
