export interface Term {
  term: string;
  en?: string;
  tag: "Rust" | "Böngésző" | "Web" | "Hálózat" | "Eszköz";
  def: string;
}

export const GLOSSARY: Term[] = [
  { term: "Crate", tag: "Rust", def: "A Rust fordítási egysége és csomagja. Lehet bináris (futtatható program) vagy library (könyvtár). A külső crate-eket a crates.io-ról tölti le a Cargo, kb. úgy, mint a pip a PyPI-ról." },
  { term: "Cargo", tag: "Eszköz", def: "A Rust build-rendszere és csomagkezelője egyben: `cargo new`, `cargo run`, `cargo test`, `cargo add`." },
  { term: "Cargo.toml", tag: "Eszköz", def: "A projekt leíró fájlja: név, verzió, függőségek. Kb. a C#-os .csproj vagy a Pythonos pyproject.toml megfelelője." },
  { term: "Workspace", tag: "Eszköz", def: "Több crate egy közös projektben, közös `target` mappával és `Cargo.lock`-kal. A Rozsda így épül fel." },
  { term: "Ownership", en: "tulajdonjog", tag: "Rust", def: "Minden értéknek pontosan egy gazdája van. Amikor a gazda kikerül a hatókörből, az érték felszabadul. Így a Rustban nincs szemétgyűjtő, mégsincs memóriaszivárgás vagy dupla felszabadítás." },
  { term: "Move", tag: "Rust", def: "Amikor egy (nem Copy) értéket átadsz vagy értékül adsz, a tulajdonjog átkerül, és a régi változó többé nem használható." },
  { term: "Borrowing", en: "kölcsönzés", tag: "Rust", def: "Referencia (`&T` vagy `&mut T`) egy értékre, tulajdonjog-átadás nélkül. Szabály: egyszerre vagy sok olvasó (`&`), vagy egyetlen író (`&mut`)." },
  { term: "Borrow checker", tag: "Rust", def: "A fordító azon része, amely fordítási időben ellenőrzi a kölcsönzési szabályokat. Szigorú, de pontosan megmondja, mi a baj." },
  { term: "Lifetime", en: "élettartam", tag: "Rust", def: "Az a kódszakasz, ameddig egy referencia érvényes. Általában a fordító kikövetkezteti; ha nem, `'a` jelöléssel kell segíteni." },
  { term: "&str vs String", tag: "Rust", def: "`String`: saját, növelhető, heapen tárolt szöveg. `&str`: kölcsönzött szelet egy szövegből (string slice). Függvényparaméternek általában `&str` a jobb." },
  { term: "Struct", tag: "Rust", def: "Saját adattípus mezőkkel, mint egy C# `struct`/`class` öröklés nélkül. Metódusok az `impl` blokkban." },
  { term: "Enum", tag: "Rust", def: "Típus, amelynek értéke a felsorolt változatok egyike, és minden változat hordozhat adatot. Sokkal erősebb, mint a C#/C++ enum, inkább egy „tagged union”." },
  { term: "match", tag: "Rust", def: "Mintaillesztés. A fordító ellenőrzi, hogy minden esetet lekezeltél-e (exhaustiveness)." },
  { term: "Option<T>", tag: "Rust", def: "`Some(érték)` vagy `None`. A Rustban nincs null: ahol hiányozhat egy érték, ott Option van." },
  { term: "Result<T, E>", tag: "Rust", def: "`Ok(érték)` vagy `Err(hiba)`. A hibakezelés alapja; a `?` operátor továbbadja a hibát a hívónak." },
  { term: "Trait", tag: "Rust", def: "Viselkedés-leírás (metódusok halmaza), mint egy C#-os interface. A Rozsdában erre épül a saját/profi implementációk közötti kapcsoló." },
  { term: "Trait object (dyn Trait)", tag: "Rust", def: "Futásidőben kiválasztott implementáció (`Box<dyn Trait>`), virtuális függvénytáblával. Ezzel lehet menet közben váltani két HTML-parser között." },
  { term: "Generikus", en: "generics", tag: "Rust", def: "Típusparaméteres kód (`fn f<T: Trait>(x: T)`). Fordítási időben specializálódik, ezért nincs futásidejű költsége." },
  { term: "Iterátor", tag: "Rust", def: "Bármi, ami a `next()`-tel egymás után ad elemeket. Láncolható: `.map()`, `.filter()`, `.collect()`. Lusta: csak akkor fut, ha kéred az eredményt." },
  { term: "Closure", tag: "Rust", def: "Névtelen függvény, amely „befogja” a környezete változóit: `|x| x + 1`. Mint a C# lambda vagy a Python lambda." },
  { term: "Macro", tag: "Rust", def: "Kódot generáló kód; felkiáltójel jelöli: `println!`, `vec!`, `assert_eq!`." },
  { term: "Panic", tag: "Rust", def: "Helyreállíthatatlan hiba, a program (szál) leáll. Váratlan bugokra való; a várható hibákra a Result." },
  { term: "unwrap()", tag: "Rust", def: "Kiveszi az értéket az Option/Result-ból, vagy pánikol. Prototípusban oké, kész kódban kerülendő." },
  { term: "Böngészőmotor", en: "browser engine", tag: "Böngésző", def: "Az a rész, amely a HTML-ből, CSS-ből és JS-ből képet és interakciót csinál. Pl. Blink (Chrome), Gecko (Firefox), WebKit (Safari), Servo, Ladybird." },
  { term: "Tokenizer", en: "lexer", tag: "Böngésző", def: "A nyers szöveget értelmes egységekre (tokenekre) bontja: kezdőtag, zárótag, szöveg, komment…" },
  { term: "Parser", tag: "Böngésző", def: "A tokenekből fát épít (HTML esetén DOM-ot, CSS esetén szabálylistát, JS esetén AST-t)." },
  { term: "DOM", en: "Document Object Model", tag: "Web", def: "A HTML dokumentum fa-szerkezetű, memóriabeli ábrázolása. A JavaScript ezt látja és módosítja." },
  { term: "CSSOM", tag: "Web", def: "A stíluslapok memóriabeli modellje: szabályok, szelektorok, deklarációk." },
  { term: "Kaszkád", en: "cascade", tag: "Web", def: "Az az algoritmus, amely eldönti, több ütköző CSS-szabály közül melyik érvényes egy elemre (eredet, specificitás, sorrend)." },
  { term: "Specificitás", tag: "Web", def: "Egy szelektor „súlya” (id, class, típus darabszám). Ütközéskor a nagyobb nyer." },
  { term: "Style tree", tag: "Böngésző", def: "DOM-fa, ahol minden elemhez már a végső (számított) CSS-értékek tartoznak." },
  { term: "Layout", en: "reflow", tag: "Böngésző", def: "Annak kiszámítása, hogy minden doboz hol legyen és mekkora legyen." },
  { term: "Doboz-modell", en: "box model", tag: "Web", def: "Minden elem egy doboz: tartalom, padding, border, margin, belülről kifelé." },
  { term: "Display list", tag: "Böngésző", def: "Rajzolási parancsok listája (téglalap ide, szöveg oda), amit a raszterizáló pixelekké alakít." },
  { term: "Raszterizálás", tag: "Böngésző", def: "Alakzatokból (téglalap, görbe, betű) pixelek előállítása." },
  { term: "Hit testing", tag: "Böngésző", def: "Annak megállapítása, hogy egy kattintás melyik elemre esett." },
  { term: "Event loop", en: "eseményhurok", tag: "Web", def: "A JS futtatási modellje: egy szál, feladatsor, mikrofeladatok (Promise), és a rajzolás ütemezése." },
  { term: "WHATWG", tag: "Web", def: "Az a szervezet, amely a HTML, DOM, URL és Fetch élő szabványait írja. A böngészőmotor-írás bibliája." },
  { term: "Spec", tag: "Web", def: "Szabvány (specification). Böngészőt a spec alapján írunk, nem tippeléssel." },
  { term: "TCP", tag: "Hálózat", def: "Megbízható, sorrendtartó bájtfolyam két gép között. Erre épül a HTTP/1.1 és a HTTP/2." },
  { term: "HTTP", tag: "Hálózat", def: "Szöveges (1.1) vagy bináris (2, 3) kérés–válasz protokoll a weboldalak letöltésére." },
  { term: "TLS", tag: "Hálózat", def: "Titkosító réteg a TCP fölött; ettől lesz a HTTP-ből HTTPS." },
  { term: "DNS", tag: "Hálózat", def: "A domain nevekből (example.com) IP-címet csináló rendszer." },
  { term: "WebExtensions", tag: "Web", def: "A Chrome, a Firefox és az Edge közös bővítmény-API-ja: manifest.json, content scriptek, háttérszkript." },
  { term: "Feature flag", tag: "Rust", def: "Cargo feature: fordítási időben ki-/bekapcsolható kódrészek és függőségek. A profi crate-eket így tesszük opcionálissá." },
  { term: "rust-analyzer", tag: "Eszköz", def: "A Rust nyelvi szervere: kódkiegészítés, típusok mutatása, hibák a szerkesztőben." },
  { term: "Clippy", tag: "Eszköz", def: "`cargo clippy`: a Rust linter. Több száz tipp, hogy idiomatikusabb legyen a kódod." },
  { term: "rustfmt", tag: "Eszköz", def: "`cargo fmt`: automatikus kódformázó, hogy ne kelljen ezen gondolkodni." },
];
